# disable line length
Metrics/LineLength:
  Enabled: false

# disable method length
Metrics/MethodLength:
  Enabled: false

# disable class length
Metrics/ClassLength:
  Enabled: false

# disable block length
Metrics/BlockLength:
  Enabled: false